---

name: role-ci
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_datapath: '{extends: relaxed, rules: {line-length: {max: 200}}}'
  test:
    needs:
      - yamllint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - almalinux9
          - rockylinux9
          - fedora39
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: default