---

name: Role-CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning
              line-length:
                level: warning
  test:
    needs:
      - yamllint
    runs-on: self-hosted
    strategy:
      matrix:
        image:
          - almalinux9
          - rockylinux9
          - fedora39
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: iamenr0s/molecule-action@v0.0.1
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: default
